#importing the required modules
import os
import shutil

#makinng a dictionary with the file extension corresponding to the folder it will be sorted into
file_selector = {
    ".DOC":"Text Files",
    ".DOCX":"Text Files",
    ".EML":"Text Files",
    ".MSG":"Text Files",
    ".ODT":"Text Files",
    ".PAGES":"Text Files",
    ".RTF":"Text Files",
    ".TEX":"Text Files",
    ".TXT":"Text Files",
    ".WPD":"Text Files",
    ".AAE":"Data Files",
    ".BIN":"Data Files",
    ".CSV":"Data Files",
    ".DAT":"Data Files",
    ".KEY":"Data Files",
    ".LOG":"Data Files",
    ".MPP":"Data Files",
    ".OBB":"Data Files",
    ".PPT":"Data Files",
    ".PPTX":"Data Files",
    ".RPT":"Data Files",
    ".TAR":"Data Files",
    ".VCF":"Data Files",
    ".XML":"Data Files",
    ".AIF":"Audio Files",
    ".FLAC":"Audio Files",
    ".M3U":"Audio Files",
    ".M4A":"Audio Files",
    ".MID":"Audio Files",
    ".MP3":"Audio Files",
    ".OGG":"Audio Files",
    ".WAV":"Audio Files",
    ".WMA":"Audio Files",
    ".3GP":"Video Files",
    ".ASF":"Video Files",
    ".AVI":"Video Files",
    ".FLV":"Video Files",
    ".M4V":"Video Files",
    ".MOV":"Video Files",
    ".MP4":"Video Files",
    ".MPG":"Video Files",
    ".SWF":"Video Files",
    ".TS":"Video Files",
    ".VOB":"Video Files",
    ".WMV":"Video Files",
    ".3DM":"3D Image Files",
    ".3DS":"3D Image Files",
    ".BLEND":"3D Image Files",
    ".DAE":"3D Image Files",
    ".FBX":"3D Image Files",
    ".MAX":"3D Image Files",
    ".OBJ":"3D Image Files",
    ".BMP":"Raster Image Files",
    ".DCM":"Raster Image Files",
    ".DDS":"Raster Image Files",
    ".DJVU":"Raster Image Files",
    ".GIF":"Raster Image Files",
    ".HEIC":"Raster Image Files",
    ".JPG":"Raster Image Files",
    ".PNG":"Raster Image Files",
    ".PSD":"Raster Image Files",
    ".TGA":"Raster Image Files",
    ".TIF":"Raster Image Files",
    ".AI":"Vector Image Files",
    ".CDR":"Vector Image Files",
    ".EMF":"Vector Image Files",
    ".EPS":"Vector Image Files",
    ".PS":"Vector Image Files",
    ".SKETCH":"Vector Image Files",
    ".SVG":"Vector Image Files",
    ".VSDX":"Vector Image Files",
    ".INDD":"Page Layout Files",
    ".OXPS":"Page Layout Files",
    ".PDF":"Page Layout Files",
    ".PMD":"Page Layout Files",
    ".PUB":"Page Layout Files",
    ".QXP":"Page Layout Files",
    ".XPS":"Page Layout Files",
    ".NUMBERS":"Spreadsheet Files",
    ".ODS":"Spreadsheet Files",
    ".XLR":"Spreadsheet Files",
    ".XLS":"Spreadsheet Files",
    ".XLSX":"Spreadsheet Files",
    ".ACCDB":"Database Files",
    ".CRYPT14":"Database Files",
    ".DB":"Database Files",
    ".MDB":"Database Files",
    ".ODB":"Database Files",
    ".PDB":"Database Files",
    ".SQL":"Database Files",
    ".SQLITE":"Database Files",
    ".APK":"Executable Files",
    ".APP":"Executable Files",
    ".BAT":"Executable Files",
    ".BIN":"Executable Files",
    ".CMD":"Executable Files",
    ".COM":"Executable Files",
    ".EXE":"Executable Files",
    ".IPA":"Executable Files",
    ".JAR":"Executable Files",
    ".RUN":"Executable Files",
    ".SH":"Executable Files",
    ".BIN":"Game Files",
    ".DEM":"Game Files",
    ".GAM":"Game Files",
    ".GBA":"Game Files",
    ".NES":"Game Files",
    ".PAK":"Game Files",
    ".PKG":"Game Files",
    ".ROM":"Game Files",
    ".SAV":"Game Files",
    ".DGN":"CAD Files",
    ".DWG":"CAD Files",
    ".DXF":"CAD Files",
    ".STEP":"CAD Files",
    ".STL":"CAD Files",
    ".STP":"CAD Files",
    ".GPX":"GIS Files",
    ".KML":"GIS Files",
    ".KMZ":"GIS Files",
    ".OSM":"GIS Files",
    ".ASP":"Web Files",
    ".ASPX":"Web Files",
    ".CER":"Web Files",
    ".CFM":"Web Files",
    ".CSR":"Web Files",
    ".CSS":"Web Files",
    ".HTML":"Web Files",
    ".JS":"Web Files",
    ".JSON":"Web Files",
    ".JSP":"Web Files",
    ".PHP":"Web Files",
    ".XHTML":"Web Files",
    ".CRX":"Plugin Files",
    ".ECF":"Plugin Files",
    ".PLUGIN":"Plugin Files",
    ".SAFARIEXTZ":"Plugin Files",
    ".XPI":"Plugin Files",
    ".FNT":"Font Files",
    ".OTF":"Font Files",
    ".TTF":"Font Files",
    ".WOFF":"Font Files",
    ".WOFF2":"Font Files",
    ".ANI":"System Files",
    ".CAB":"System Files",
    ".CPL":"System Files",
    ".CUR":"System Files",
    ".DESKTHEMEPACK":"System Files",
    ".DLL":"System Files",
    ".DMP":"System Files",
    ".DRV":"System Files",
    ".ICNS":"System Files",
    ".ICO":"System Files",
    ".LNK":"System Files",
    ".REG":"System Files",
    ".SYS":"System Files",
    ".CFG":"Settings Files",
    ".INI":"Settings Files",
    ".PKG":"Settings Files",
    ".SET":"Settings Files",
    ".ASC":"Encoded Files",
    ".BIN":"Encoded Files",
    ".ENC":"Encoded Files",
    ".MIM":"Encoded Files",
    ".UUE":"Encoded Files",
    ".7Z":"Compressed Files",
    ".CBR":"Compressed Files",
    ".DEB":"Compressed Files",
    ".GZ":"Compressed Files",
    ".PKG":"Compressed Files",
    ".RAR":"Compressed Files",
    ".RPM":"Compressed Files",
    ".TAR.GZ":"Compressed Files",
    ".XAPK":"Compressed Files",
    ".ZIP":"Compressed Files",
    ".ZIPX":"Compressed Files",
    ".BIN":"Disk Image Files",
    ".DMG":"Disk Image Files",
    ".IMG":"Disk Image Files",
    ".ISO":"Disk Image Files",
    ".MDF":"Disk Image Files",
    ".ROM":"Disk Image Files",
    ".VCD":"Disk Image Files",
    ".APPX":"Developer Files",
    ".C":"Developer Files",
    ".CLASS":"Developer Files",
    ".CONFIG":"Developer Files",
    ".CPP":"Developer Files",
    ".CS":"Developer Files",
    ".H":"Developer Files",
    ".JAVA":"Developer Files",
    ".KT":"Developer Files",
    ".LUA":"Developer Files",
    ".M":"Developer Files",
    ".MD":"Developer Files",
    ".PL":"Developer Files",
    ".PY":"Developer Files",
    ".SB3":"Developer Files",
    ".SLN":"Developer Files",
    ".SWIFT":"Developer Files",
    ".UNITY":"Developer Files",
    ".VB":"Developer Files",
    ".VCXPROJ":"Developer Files",
    ".XCODEPROJ":"Developer Files",
    ".YML":"Developer Files",
    ".ABK":"Backup Files",
    ".ARC":"Backup Files",
    ".BAK":"Backup Files",
    ".TMP":"Backup Files",
    ".CRDOWNLOAD":"Misc Files",
    ".ICS":"Misc Files",
    ".MSI":"Misc Files",
    ".NOMEDIA":"Misc Files",
    ".PART":"Misc Files",
    ".PKPASS":"Misc Files",
    ".SRT":"Misc Files",
    ".TORRENT":"Misc Files",
}
